### ISSUE TITLE
Event-citizen error

### ISSUE THREAD

**Issue by FyRoOxX** [NanoDankster/skript-npc#4]
### Issue

> Small description of the issue.

The event value "event-citizen" create errors ...

### Errors

> Errors.
![image](https://user-images.githubusercontent.com/45236268/48848186-9f211e00-eda3-11e8-81b2-7e3799dc0902.png)

> on citizen create:
	make event-citizen sneak

### Server Information

> Spigot 1.11.2 RO-R1.0-SNAPSHOT

> Skript 2.2-Dev37c

> skript-npc 0.1.2

**Comment by NanoDankster** [comment]
Since I don't have my computer, I'll look at the issue later. Let me just mark this. 
I recommend [Skellett](https://github.com/TheLimeGlass/Skellett) and [skRayFall](https://github.com/eyesniper2/skRayFall) for Citizens right now. These addons are getting updates frequently.

**Comment by FyRoOxX** [comment]
Yes but you have the "move" feature and I think it's the best for my server ...

**Comment by FyRoOxX** [comment]
Hello, i've a question, how can I sit an npc when i click on it ?
```
on right click on entity:
	make event-citizen sit #Return an error, "not a type.citizens in a click event ...."
```
